### ISSUE TITLE
Bot behaviour contradicts description

### ISSUE THREAD

**Issue by dev2718** [researchstudio-sat/bot-skeleton#11]
As discussed in person with the Hackathon-Team and on Slack, the bot does not 
"...send you a message everytime an atom is created...", it only ever sends it's greeting message.

**Comment by fkleedorfer** [comment]
@quasarchimaere works as expected?

**Comment by quasarchimaere** [comment]
as i wrote in our slack channel where i was asked the same question. no this is not as expected and the bot should in fact send a message about an atomcreation to every connection, however the connections are not added to the botcontextwrapper due to the connectResultEvent after the connectMessage that the bot sends out is not being called anymore (for whatever reason)
